# Generated by Django 5.2.17 on 2026-08-15 08:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('exams', '0002_initial'),
        ('submissions', '0001_initial'),
        ('tenants', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GradeModeration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('PENDING', 'Pending Chief Review'), ('APPROVED', 'Approved & Moderated'), ('RETURNED', 'Returned for Revision')], default='PENDING', max_length=20)),
                ('moderation_notes', models.TextField(blank=True, help_text='Chief Examiner moderation feedback or revision directions.')),
                ('total_final_score', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('is_passed', models.BooleanField(default=False)),
                ('moderated_at', models.DateTimeField(blank=True, null=True)),
                ('attempt', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='grade_moderation', to='submissions.examattempt')),
                ('moderator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='moderated_attempts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Grade Moderation Record',
                'verbose_name_plural': 'Grade Moderation Records',
                'ordering': ['-moderated_at'],
            },
        ),
        migrations.CreateModel(
            name='GraderAllocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('candidate_range_start', models.PositiveIntegerField(help_text='Starting sequential candidate index (e.g. 1)')),
                ('candidate_range_end', models.PositiveIntegerField(help_text='Ending sequential candidate index (e.g. 100)')),
                ('sla_deadline', models.DateTimeField(blank=True, help_text='SLA evaluation deadline for this batch.', null=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('IN_PROGRESS', 'In Progress'), ('COMPLETED', 'Completed & Signed Off')], default='PENDING', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grader_allocations', to='exams.exam')),
                ('grader', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assigned_grading_allocations', to=settings.AUTH_USER_MODEL)),
                ('section_scope', models.ForeignKey(blank=True, help_text='Optional section specialization (leave blank for all subjective sections).', null=True, on_delete=django.db.models.deletion.SET_NULL, to='exams.examsection')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_related', to='tenants.tenant')),
            ],
            options={
                'verbose_name': 'Grader Allocation',
                'verbose_name_plural': 'Grader Allocations',
                'ordering': ['candidate_range_start'],
            },
        ),
        migrations.CreateModel(
            name='QuestionScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('awarded_marks', models.DecimalField(decimal_places=2, default=0.0, max_digits=6)),
                ('rubric_breakdown', models.JSONField(blank=True, default=dict, help_text="Per-criterion score map: {'rubric_id_1': 4.5, 'rubric_id_2': 3.0}")),
                ('examiner_notes', models.TextField(blank=True, help_text='Private internal moderation notes.')),
                ('feedback_to_student', models.TextField(blank=True, help_text='Constructive remarks revealed to student only after results are published.')),
                ('is_draft', models.BooleanField(default=True, help_text='True if evaluation is in-progress; False when finalized by grader.')),
                ('version', models.PositiveIntegerField(default=1, help_text='Optimistic concurrency control version lock.')),
                ('graded_at', models.DateTimeField(auto_now=True)),
                ('answer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='grade_record', to='submissions.attemptanswer')),
                ('grader', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='graded_scores', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Question Score',
                'verbose_name_plural': 'Question Scores',
                'ordering': ['-graded_at'],
            },
        ),
    ]
