# Generated by Django 5.2.17 on 2026-08-15 07:50

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('exams', '0002_initial'),
        ('questions', '0001_initial'),
        ('tenants', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ExamAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resume_token', models.CharField(db_index=True, default=uuid.uuid4, help_text='Cryptographic session resume token for crash recovery.', max_length=64, unique=True)),
                ('candidate_seed', models.BigIntegerField(help_text='Deterministic seed for reproducible randomized shuffling of questions and options.')),
                ('started_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('bonus_minutes_awarded', models.PositiveIntegerField(default=0, help_text='Dynamic time added on-the-fly by Designer in Live Ops.')),
                ('status', models.CharField(choices=[('IN_PROGRESS', 'In Progress'), ('SUBMITTED', 'Submitted'), ('AUTO_SUBMITTED', 'Auto-Submitted (Expired / Violations)'), ('DISQUALIFIED', 'Disqualified')], default='IN_PROGRESS', max_length=20)),
                ('last_heartbeat', models.DateTimeField(default=django.utils.timezone.now)),
                ('violation_count', models.PositiveIntegerField(default=0)),
                ('client_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('is_simulation', models.BooleanField(default=False, help_text='True if run as a dry-run test sandbox by Designer / Item Writer. Excluded from official results.')),
                ('current_question', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='active_in_attempts', to='questions.question')),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to='exams.exam')),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exam_attempts', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_related', to='tenants.tenant')),
            ],
            options={
                'verbose_name': 'Exam Attempt',
                'verbose_name_plural': 'Exam Attempts',
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='AttemptLifelineUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lifeline_type', models.CharField(choices=[('SKIP_QUESTION', 'Skip Question'), ('FIFTY_FIFTY', '50:50 Eliminator'), ('HINT_TOKEN', 'Hint Token'), ('BOOKMARK_FLAG', 'Bookmark / Flag')], max_length=30)),
                ('details', models.JSONField(blank=True, default=dict, help_text="e.g. {'eliminated_option_ids': [12, 15]} for 50:50, or {'hint_shown': true}")),
                ('used_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lifeline_usages', to='questions.question')),
                ('attempt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lifeline_usages', to='submissions.examattempt')),
            ],
            options={
                'verbose_name': 'Attempt Lifeline Usage',
                'verbose_name_plural': 'Attempt Lifeline Usages',
                'ordering': ['-used_at'],
            },
        ),
        migrations.CreateModel(
            name='ProctoringLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('FULLSCREEN_ENTER', 'Entered Fullscreen'), ('FULLSCREEN_EXIT', 'Exited Fullscreen Lockdown'), ('TAB_BLUR', 'Window Lost Focus / Tab Switched'), ('CLIPBOARD_BLOCKED', 'Copy / Paste Attempt Intercepted'), ('DEVTOOLS_BLOCKED', 'Developer Tools / Inspect Key Intercepted'), ('HEARTBEAT_DISCONNECTED', 'Heartbeat Signal Disconnected'), ('HEARTBEAT_RECONNECTED', 'Heartbeat Signal Reconnected'), ('LIFELINE_USED', 'Lifeline Executed'), ('AUTO_SUBMISSION', 'Auto-Submission Triggered')], max_length=30)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('details', models.JSONField(blank=True, default=dict)),
                ('attempt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proctoring_logs', to='submissions.examattempt')),
            ],
            options={
                'verbose_name': 'Proctoring Log',
                'verbose_name_plural': 'Proctoring Logs',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='AttemptAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text_response', models.TextField(blank=True, default='')),
                ('is_bookmarked', models.BooleanField(default=False)),
                ('is_skipped', models.BooleanField(default=False)),
                ('order_in_attempt', models.PositiveIntegerField(default=1)),
                ('saved_at', models.DateTimeField(auto_now=True)),
                ('marks_awarded', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('is_graded', models.BooleanField(default=False)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempt_answers', to='questions.question')),
                ('selected_options', models.ManyToManyField(blank=True, related_name='selected_in_answers', to='questions.questionoption')),
                ('attempt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='submissions.examattempt')),
            ],
            options={
                'verbose_name': 'Attempt Answer',
                'verbose_name_plural': 'Attempt Answers',
                'ordering': ['order_in_attempt'],
                'unique_together': {('attempt', 'question')},
            },
        ),
    ]
