# Generated by Django 5.2.17 on 2026-08-16 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submissions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attemptlifelineusage',
            name='lifeline_type',
            field=models.CharField(choices=[('FIFTY_FIFTY', '50:50 Eliminator'), ('HINT_TOKEN', 'Hint Token'), ('BOOKMARK_FLAG', 'Bookmark / Flag')], max_length=30),
        ),
    ]
