# Generated by Django 5.2.17 on 2026-08-14 20:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenants', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='QuestionBank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('code', models.CharField(blank=True, help_text='e.g. CS101-BANK, MATH-ADV', max_length=50)),
                ('subject', models.CharField(help_text='Academic discipline or course code', max_length=150)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_question_banks', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_related', to='tenants.tenant')),
            ],
            options={
                'verbose_name': 'Question Bank',
                'verbose_name_plural': 'Question Banks',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_type', models.CharField(choices=[('MCQ_SINGLE', 'Single Choice MCQ'), ('MCQ_MULTIPLE', 'Multiple Choice MCQ'), ('IMAGE_MCQ', 'Picture / Diagram MCQ'), ('SHORT_ANSWER', 'Short Answer'), ('LONG_ESSAY', 'Long Essay / Structured')], db_index=True, default='MCQ_SINGLE', max_length=20)),
                ('prompt', models.TextField(help_text='Primary question text or instructions.')),
                ('image_asset', models.ImageField(blank=True, help_text='High-resolution diagram, chart, or visual asset for diagram-based questions.', null=True, upload_to='questions/diagrams/')),
                ('points', models.DecimalField(decimal_places=2, default=1.0, help_text='Base marks allocated to this question.', max_digits=6)),
                ('negative_points', models.DecimalField(decimal_places=2, default=0.0, help_text='Penalty points deducted for an incorrect response.', max_digits=6)),
                ('difficulty', models.CharField(choices=[('EASY', 'Easy'), ('MEDIUM', 'Medium'), ('HARD', 'Hard')], db_index=True, default='MEDIUM', max_length=10)),
                ('blooms_level', models.CharField(choices=[('REMEMBER', 'Remember'), ('UNDERSTAND', 'Understand'), ('APPLY', 'Apply'), ('ANALYZE', 'Analyze'), ('EVALUATE', 'Evaluate'), ('CREATE', 'Create')], db_index=True, default='REMEMBER', max_length=15)),
                ('topic_tags', models.CharField(blank=True, help_text='Comma-separated topic keywords (e.g. recursion, arrays, sorting).', max_length=255)),
                ('model_answer', models.TextField(blank=True, help_text='Confidential model answer and scoring guidelines for human evaluators.')),
                ('hint_text', models.CharField(blank=True, help_text='Hint revealed if candidate consumes a Hint Token lifeline.', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='authored_questions', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_related', to='tenants.tenant')),
                ('bank', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='questions.questionbank')),
            ],
            options={
                'verbose_name': 'Question',
                'verbose_name_plural': 'Questions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='QuestionOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('option_text', models.CharField(max_length=500)),
                ('option_image', models.ImageField(blank=True, help_text='Optional diagram for this specific choice option.', null=True, upload_to='questions/options/')),
                ('is_correct', models.BooleanField(default=False)),
                ('order', models.PositiveIntegerField(default=0)),
                ('explanation', models.TextField(blank=True, help_text='Post-exam explanation of why this option is correct/incorrect.')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='questions.question')),
            ],
            options={
                'verbose_name': 'Question Option',
                'verbose_name_plural': 'Question Options',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='QuestionRubric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criteria_title', models.CharField(help_text='e.g. Methodology, Code Correctness, Analysis', max_length=200)),
                ('description', models.TextField(blank=True, help_text='Guidelines for awarding full vs partial points')),
                ('max_points', models.DecimalField(decimal_places=2, max_digits=6)),
                ('order', models.PositiveIntegerField(default=0)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rubrics', to='questions.question')),
            ],
            options={
                'verbose_name': 'Question Rubric Criteria',
                'verbose_name_plural': 'Question Rubric Criteria',
                'ordering': ['order', 'id'],
            },
        ),
    ]
