# Generated by Django 5.2.17 on 2026-08-14 19:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenants', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DataImportJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('import_type', models.CharField(choices=[('PARTICIPANT_ROSTER', 'Participant Exam Roster (CSV/Excel)'), ('QUESTION_BANK', 'Question Bank (CSV/Excel/JSON)'), ('FACULTY_USERS', 'Faculty / Graders / Item Writers (CSV/Excel)'), ('RUBRIC_TEMPLATES', 'Grading Rubrics (CSV/JSON)'), ('EXAM_BLUEPRINT', 'Complete Exam Blueprint (JSON/YAML)')], db_index=True, max_length=30)),
                ('status', models.CharField(choices=[('PENDING', 'Upload Received'), ('VALIDATING', 'Dry-Run Validation In Progress'), ('PREVIEW_READY', 'Validation Passed — Awaiting Confirmation'), ('PROCESSING', 'Committing Records'), ('COMPLETED', 'Import Successfully Completed'), ('FAILED', 'Import Failed (Validation Errors)')], db_index=True, default='PENDING', max_length=20)),
                ('file_format', models.CharField(choices=[('CSV', 'CSV (.csv)'), ('XLSX', 'Microsoft Excel (.xlsx)'), ('JSON', 'JSON (.json)')], default='CSV', max_length=10)),
                ('source_file', models.FileField(upload_to='imports/raw/%Y/%m/')),
                ('total_rows', models.PositiveIntegerField(default=0)),
                ('processed_rows', models.PositiveIntegerField(default=0)),
                ('successful_rows', models.PositiveIntegerField(default=0)),
                ('failed_rows', models.PositiveIntegerField(default=0)),
                ('preview_data', models.JSONField(blank=True, default=list)),
                ('error_log', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='initiated_imports', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_related', to='tenants.tenant')),
            ],
            options={
                'db_table': 'opti_data_import_jobs',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['tenant', 'import_type', 'status'], name='opti_data_i_tenant__7b2d33_idx')],
            },
        ),
    ]
