# Generated by Django 5.2.17 on 2026-08-14 19:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tenant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Institutional display name', max_length=200)),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('domain', models.CharField(blank=True, help_text='Custom domain (optional)', max_length=255, null=True, unique=True)),
                ('tier', models.CharField(choices=[('STARTER', 'Starter (Single School / Lab, max 100 concurrent)'), ('PROFESSIONAL', 'Professional (College / Multi-dept, max 500 concurrent)'), ('ENTERPRISE', 'Enterprise (University / Multi-campus, unlimited)')], default='STARTER', max_length=20)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('max_concurrent_candidates', models.PositiveIntegerField(default=100)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='tenants/logos/')),
                ('primary_color', models.CharField(default='#4F46E5', help_text='Hex color code for institutional branding', max_length=7)),
                ('contact_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'opti_tenants',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='TenantFeatureFlag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feature_key', models.CharField(choices=[('LIVE_PROCTORING', 'Live Anti-Cheating & Proctoring'), ('LIFELINES_ENGINE', 'Exam Lifelines System'), ('DOUBLE_BLIND_GRADING', 'Double-Blind Anonymized Evaluation'), ('DYNAMIC_TIME_EXT', 'Live Ops Time Extension'), ('ADVANCED_ANALYTICS', 'Cohort Analytics & PDF Scorecards'), ('GRADE_MODERATION', 'Chief Examiner Grade Moderation'), ('CSV_ROSTER_IMPORT', 'Bulk CSV Participant Roster Import')], max_length=50)),
                ('is_enabled', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feature_flags', to='tenants.tenant')),
            ],
            options={
                'db_table': 'opti_tenant_feature_flags',
                'unique_together': {('tenant', 'feature_key')},
            },
        ),
    ]
