# Generated by Django 5.2.17 on 2026-08-14 20:22

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenants', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ExamQuestionAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=1)),
                ('custom_marks', models.DecimalField(blank=True, decimal_places=2, help_text='Overrides base question points specifically for this exam.', max_digits=6, null=True)),
            ],
            options={
                'verbose_name': 'Exam Question Assignment',
                'verbose_name_plural': 'Exam Question Assignments',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ExamSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='e.g. Section A - Objective MCQs', max_length=150)),
                ('description', models.TextField(blank=True)),
                ('order', models.PositiveIntegerField(default=1)),
                ('weightage', models.DecimalField(decimal_places=2, default=100.0, help_text='Percentage weightage or marks allocated to this section.', max_digits=5)),
            ],
            options={
                'verbose_name': 'Exam Section',
                'verbose_name_plural': 'Exam Sections',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Exam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('code', models.CharField(help_text='Unique exam identifier (e.g. MID-2026-CS101)', max_length=50)),
                ('subject', models.CharField(help_text='Discipline or Course Title', max_length=150)),
                ('description', models.TextField(blank=True)),
                ('instructions', models.TextField(blank=True, help_text='Detailed examination instructions and rules presented in the pre-exam lobby.')),
                ('start_time', models.DateTimeField(help_text='Start of the permitted schedule window.')),
                ('end_time', models.DateTimeField(help_text='End of the permitted schedule window.')),
                ('duration_minutes', models.PositiveIntegerField(default=60, help_text='Individual candidate examination duration limit.')),
                ('total_marks', models.DecimalField(decimal_places=2, default=100.0, max_digits=6)),
                ('passing_percentage', models.DecimalField(decimal_places=2, default=40.0, max_digits=5)),
                ('enforce_fullscreen', models.BooleanField(default=True, help_text='Locks candidate into full-screen lockdown mode.')),
                ('max_tab_switch_limit', models.PositiveIntegerField(default=3, help_text='Maximum allowed tab blur/switches before auto-submission.')),
                ('lock_copy_paste', models.BooleanField(default=True, help_text='Disables clipboard copy/cut/paste events.')),
                ('shuffle_questions', models.BooleanField(default=True, help_text='Randomizes question delivery order per student.')),
                ('shuffle_options', models.BooleanField(default=True, help_text='Randomizes choice options per question.')),
                ('allow_back_navigation', models.BooleanField(default=True, help_text='Allows candidates to navigate back to previous questions.')),
                ('results_published', models.BooleanField(default=False, help_text='When True, candidates can inspect scores and feedback.')),
                ('is_active', models.BooleanField(default=True, help_text='Controls if this exam blueprint is active.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_exams', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_related', to='tenants.tenant')),
            ],
            options={
                'verbose_name': 'Exam',
                'verbose_name_plural': 'Exams',
                'ordering': ['-start_time', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ExamLifelineConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lifeline_type', models.CharField(choices=[('SKIP_QUESTION', 'Skip Question'), ('FIFTY_FIFTY', '50:50 Eliminator'), ('HINT_TOKEN', 'Hint Token'), ('BOOKMARK_FLAG', 'Bookmark / Flag')], max_length=30)),
                ('is_enabled', models.BooleanField(default=True)),
                ('max_allowed', models.PositiveIntegerField(default=1, help_text='Maximum allowed uses per candidate during the exam.')),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lifeline_configs', to='exams.exam')),
            ],
            options={
                'verbose_name': 'Exam Lifeline Configuration',
                'verbose_name_plural': 'Exam Lifeline Configurations',
            },
        ),
        migrations.CreateModel(
            name='ExamParticipantRoster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('candidate_index', models.PositiveIntegerField(db_index=True, help_text='Sequential integer 1..N assigned for double-blind grader allocation.')),
                ('registration_number', models.CharField(blank=True, max_length=50)),
                ('status', models.CharField(choices=[('ENROLLED', 'Enrolled'), ('ABSENT', 'Absent'), ('REVOKED', 'Revoked / Barred')], default='ENROLLED', max_length=20)),
                ('enrolled_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='roster_entries', to='exams.exam')),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrolled_exam_rosters', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Exam Participant Roster Entry',
                'verbose_name_plural': 'Exam Participant Roster Entries',
                'ordering': ['candidate_index'],
            },
        ),
    ]
