# Generated by Django 5.2.17 on 2026-08-14 20:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('exams', '0001_initial'),
        ('questions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='examquestionassignment',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exam_assignments', to='questions.question'),
        ),
        migrations.AddField(
            model_name='examsection',
            name='exam',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='exams.exam'),
        ),
        migrations.AddField(
            model_name='examquestionassignment',
            name='section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='exams.examsection'),
        ),
        migrations.AlterUniqueTogether(
            name='exam',
            unique_together={('tenant', 'code')},
        ),
        migrations.AlterUniqueTogether(
            name='examlifelineconfig',
            unique_together={('exam', 'lifeline_type')},
        ),
        migrations.AlterUniqueTogether(
            name='examparticipantroster',
            unique_together={('exam', 'candidate_index'), ('exam', 'participant')},
        ),
        migrations.AlterUniqueTogether(
            name='examquestionassignment',
            unique_together={('section', 'question')},
        ),
    ]
