# Generated by Django 5.2.17 on 2026-08-15 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0003_exam_published_at_exam_published_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='examquestionassignment',
            name='is_reserve',
            field=models.BooleanField(default=False, help_text='Designated as a reserve pool item for Question Swap / Skip lifelines.'),
        ),
    ]
